import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from 'components/Header'
import HeroSection from 'components/HeroSection'
import EducationForEveryone from 'components/EducationForEveryone'
import TopCources from 'components/TopCources'
import DistanceLearning from 'components/DistanceLearning'
import Footer from 'components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tutor Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main className={styles.main}>
        <Header />
        <HeroSection />
        <EducationForEveryone />
        <TopCources/>
        <DistanceLearning/>
        <Footer/>
      </main>
    </>
  )
}


